import { NextResponse } from 'next/server';
import { generateAdminCourseQuiz } from '@/lib/server/adminCourseAI';
import { requireAdmin } from '@/lib/auth/requireAdmin';
import { isAllowedWriteOrigin } from '@/lib/security/originGuard';
import { logSystemEvent } from '@/lib/utils/logger';

function detectLanguageMode(topic: string): 'english' | 'hinglish' {
  if (/[\u0900-\u097F]/.test(topic)) {
    return 'hinglish';
  }

  if (/\b(hinglish|hindi|हिंदी|हिन्दी)\b/i.test(topic)) {
    return 'hinglish';
  }

  return 'english';
}

export async function POST(request: Request) {
  try {
    if (!isAllowedWriteOrigin(request)) {
      await logSystemEvent('WARN', 'admin_generate_quiz', 'Blocked quiz generation due to invalid origin.');
      return NextResponse.json({ ok: false, message: 'Invalid request origin.' }, { status: 403 });
    }

    const admin = await requireAdmin(request);
    if (!admin.ok) {
      return admin.response;
    }

    const { session } = admin;

    const body = (await request.json().catch(() => ({}))) as {
      topic?: string;
      count?: number;
      language?: 'english' | 'hinglish' | 'auto';
    };
    const topic = typeof body.topic === 'string' ? body.topic.trim() : '';
    const count = typeof body.count === 'number' ? Math.min(10, Math.max(1, Math.round(body.count))) : 10;
    const requestedLanguage = body.language;
    const languageMode =
      requestedLanguage === 'english' || requestedLanguage === 'hinglish'
        ? requestedLanguage
        : detectLanguageMode(topic);
    const apiKey = process.env.SARVAM_API_KEY;

    if (!apiKey) {
      await logSystemEvent(
        'ERROR',
        'admin_generate_quiz',
        'Missing SARVAM_API_KEY while generating quiz.',
        { actorAdminId: session.user._id.toString() },
        session.user._id.toString()
      );
      return NextResponse.json({ ok: false, message: 'SARVAM_API_KEY is missing.' }, { status: 500 });
    }

    if (!topic) {
      await logSystemEvent(
        'WARN',
        'admin_generate_quiz',
        'Rejected quiz generation due to missing topic.',
        { actorAdminId: session.user._id.toString() },
        session.user._id.toString()
      );
      return NextResponse.json({ ok: false, message: 'A valid topic is required.' }, { status: 400 });
    }

    const questions = await generateAdminCourseQuiz(topic, apiKey, count, languageMode);

    await logSystemEvent(
      'INFO',
      'admin_generate_quiz',
      'Quiz generated by admin.',
      { actorAdminId: session.user._id.toString(), topic, count, languageMode },
      session.user._id.toString()
    );

    return NextResponse.json({ ok: true, questions });
  } catch (error) {
    await logSystemEvent(
      'ERROR',
      'admin_generate_quiz',
      'Quiz generation route failed.',
      { error: error instanceof Error ? error.message : 'Unknown error' }
    );

    const details = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json(
      {
        ok: false,
        message: 'Failed to generate the admin course quiz.',
        details: process.env.NODE_ENV === 'development' ? details : undefined,
      },
      { status: 500 }
    );
  }
}
