import { randomUUID } from 'crypto';
import { NextResponse } from 'next/server';
import { recordOpsMetric } from '@/lib/server/opsTelemetry';
import { requireAuthenticated } from '@/lib/auth/requireAuthenticated';

const BASE_URL = 'https://api.sarvam.ai';
const TTS_TIMEOUT_MS = 18000;

function safeError(message: string, status: number) {
  return NextResponse.json({ error: message }, { status });
}

function withCorrelation<T extends NextResponse>(response: T, correlationId: string): T {
  response.headers.set('x-correlation-id', correlationId);
  return response;
}

export async function POST(request: Request) {
  const correlationId = request.headers.get('x-correlation-id')?.trim() || randomUUID();

  try {
    const auth = await requireAuthenticated(request);
    if (!auth.ok) {
      return withCorrelation(auth.response, correlationId);
    }

    const body = await request.json();
    const apiKey = process.env.SARVAM_API_KEY;

    if (!apiKey) {
      return withCorrelation(safeError('Text-to-speech service is currently unavailable.', 503), correlationId);
    }

    // Extract text from request - support both 'text' and 'input' parameters
    const text = body.text || body.input || '';
    
    if (!text || typeof text !== 'string') {
      console.error('[TTS Proxy] Invalid or missing text:', text);
      return withCorrelation(NextResponse.json(
        { error: "Text is required for TTS" },
        { status: 400 }
      ), correlationId);
    }

    // Truncate text to 2500 characters max as per Sarvam limits
    const truncatedText = text.length > 2500 ? text.substring(0, 2500) : text;

    // Determine language code
    const langCode = body.target_language_code || body.language_code || 'en-IN';
    
    // Enforce Sarvam Bulbul v3 for all speech generation requests.
    const speaker = body.speaker || (langCode === 'hi-IN' ? 'shubh' : 'amelia');
    const payload = {
      text: truncatedText,
      target_language_code: langCode,
      model: 'bulbul:v3',
      speaker,
      pace: body.pace || 1.0,
      speech_sample_rate: body.speech_sample_rate || 24000,
    };

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), TTS_TIMEOUT_MS);

    const response = await fetch(`${BASE_URL}/text-to-speech`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'API-Subscription-Key': apiKey,
      },
      body: JSON.stringify(payload),
      signal: controller.signal,
    }).finally(() => {
      clearTimeout(timeoutId);
    });

    console.log('[TTS Proxy] Response status:', response.status);

    if (!response.ok) {
      const errData = await response.json().catch(() => ({}));
      const safeMessage =
        response.status >= 500
          ? 'Text-to-speech provider is temporarily unavailable.'
          : (typeof errData?.message === 'string' ? errData.message : 'Text-to-speech request failed.');
      return withCorrelation(safeError(safeMessage, response.status), correlationId);
    }

    const data = await response.json();
    
    // Validate response has audio content
    if (!data.audios || !Array.isArray(data.audios) || data.audios.length === 0) {
      return withCorrelation(safeError('No audio generated by text-to-speech service.', 502), correlationId);
    }

    return withCorrelation(NextResponse.json(data), correlationId);
  } catch (error) {
    if (error instanceof Error && error.name === 'AbortError') {
      recordOpsMetric('sarvam_tts_timeout');
      return withCorrelation(safeError('Text-to-speech request timed out. Please try again.', 504), correlationId);
    }

    recordOpsMetric('sarvam_tts_error');
    return withCorrelation(safeError('Text-to-speech service failed.', 500), correlationId);
  }
}
