import { NextResponse } from 'next/server';
import { getMongoDb } from '@/lib/mongodb';
import { COLLECTIONS } from '@/lib/db/collections';
import { resolveSessionUser } from '@/lib/auth/session';
import { ObjectId } from 'mongodb';
import { logSystemEvent } from '@/lib/utils/logger';
import { isAllowedWriteOrigin } from '@/lib/security/originGuard';

function generateNumericCode(): string {
  return Math.floor(100000 + Math.random() * 900000).toString();
}

export async function POST(
  request: Request,
  props: { params: Promise<{ userId: string }> }
) {
  try {
    if (!isAllowedWriteOrigin(request)) {
      return NextResponse.json({ ok: false, message: 'Invalid request origin.' }, { status: 403 });
    }

    const db = await getMongoDb();
    const sessionToken = await resolveSessionUser(db, request);
    if (!sessionToken || sessionToken.user.role !== 'admin') {
      return NextResponse.json({ ok: false, message: 'Unauthorized. Admin access required.' }, { status: 403 });
    }

    const { userId } = await props.params;

    let targetObjectId;
    try {
      targetObjectId = new ObjectId(userId);
    } catch {
      return NextResponse.json({ ok: false, message: 'Invalid User ID format' }, { status: 400 });
    }

    const users = db.collection(COLLECTIONS.users);
    const user = await users.findOne({ _id: targetObjectId });
    if (!user) {
      return NextResponse.json({ ok: false, message: 'User not found' }, { status: 404 });
    }

    if (user.role === 'admin' && user._id.toString() !== sessionToken.user._id.toString()) {
      await logSystemEvent(
        'WARN',
        'admin_reset_password',
        'Blocked attempt to reset another admin password.',
        { actorAdminId: sessionToken.user._id.toString(), targetUserId: user._id.toString() },
        sessionToken.user._id.toString()
      );

      return NextResponse.json({ ok: false, message: 'Cannot reset password for another admin.' }, { status: 403 });
    }

    // Ensure TTL index exists for auto-deletion
    const resets = db.collection(COLLECTIONS.passwordResets);
    await resets.createIndex({ expiresAt: 1 }, { expireAfterSeconds: 0 });

    const code = generateNumericCode();
    const expiresAt = new Date(Date.now() + 2 * 60 * 1000); // 2 minutes

    await resets.updateOne(
      { userId },
      { 
        $set: { 
          code,
          expiresAt,
          createdAt: new Date()
        } 
      },
      { upsert: true }
    );

    await logSystemEvent(
      'INFO',
      'admin_reset_password',
      'Temporary password generated by admin.',
      {
        actorAdminId: sessionToken.user._id.toString(),
        targetUserId: user._id.toString(),
        expiresAt: expiresAt.toISOString(),
      },
      sessionToken.user._id.toString()
    );

    return NextResponse.json({
      ok: true,
      message: 'Temporary access code generated (valid for 2 mins).',
      temporaryPassword: code,
      expiresAt: expiresAt.toISOString(),
    });
  } catch (error) {
    console.error('Password Reset Error:', error);

    await logSystemEvent(
      'ERROR',
      'admin_reset_password',
      'Admin password reset route failed.',
      { error: error instanceof Error ? error.message : 'Unknown error' }
    );

    return NextResponse.json({ ok: false, message: 'Internal Server Error' }, { status: 500 });
  }
}
